language: node_js
node_js:
  - "stable"
services:
  - postgresql
install:
  - npm install
  - npm install -g sequelize-cli
before_script:
  - psql -c 'create database populationtestdb;' -U postgres
script:
  - npm run pretest
  - npm run test:coveralls
notifications:
  email: false
